### ISSUE TITLE
Support for Bestway Lay-Z-Spa

### ISSUE THREAD

**Issue by ctschach** [Droccal/homebridge-lay-z-spa#1]
Hi,

do you see a chance to integrate the connection to the Spa via the Bestway account/backend? Mine is a Bestway Lay-Z-Spa and using the Lay-Z-Spa App did not work.

Carsten

**Comment by Droccal** [comment]
Hey Carsten,

Not all Lay-Z Whirlpools have that Smart pump, if the App doesn‘t work for your Whirlpool then this plugin also won‘t work of course.

Sorry 

Best Regards
Thomas

**Comment by ctschach** [comment]
There is a difference between "Lay-Z-Spa" and "Bestway Lay-Z-Spa". They use different Apps and different servers. Even though the feature-set seems to be the same.

And yes, my Bestway Lay-Z-Spa also has an App connection. I successfully managed to integrate this into Homeassistant. However, adding HomeKit Support would be great...

**Comment by Droccal** [comment]
Ah okay, I didn‘t knew that!  

I can take a look - it should be no problem to integrate both Whirlpools :)
